// Code generated by command: go run asm.go -out match.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func MatchMetadata(metadata *[16]int8, hash int8) uint16
// Requires: AVX2, SSE, SSE2
TEXT ·MatchMetadata(SB), NOSPLIT, $0-18
	MOVQ         metadata+0(FP), AX
	MOVBQSX      hash+8(FP), CX
	MOVUPS       (AX), X0
	MOVDQ2Q      CX, X1
	VPBROADCASTB X1, X1
	PCMPEQB      X0, X1
	PMOVMSKB     X1, AX
	MOVW         AX, ret+16(FP)
	RET
