// Code generated by command: go run asm.go -out match.s -stubs stub.go. DO NOT EDIT.

package simd

// MatchMetadata matches |hash| against each byte in |metadata|.
func MatchMetadata(metadata *[16]int8, hash int8) uint16
